### ISSUE TITLE
macOS 下提示框的 1px 白边问题

### ISSUE THREAD

**Issue by CakeAL** [Borber/Tran#259]
![71221720148905_ pic](https://github.com/Borber/Tran/assets/46717868/18fa0e11-9843-45e2-b9b8-d0a2e0f66e22)

这里会有一个 1px 的白色边框，发现是

```css
  height: calc(100% - 1px);
```

的问题，但是通过查看 css 可知这是故意加的，但是我目前并不知道在 Windows 上显示是什么效果。

上面的
```css
html,
body {
  background: transparent;
}
```
在 macOS 上的 WebKit（Tauri 在 Mac 上使用 WebKit ）上貌似不起作用，或者说必须是白色背景。

此外，貌似有概率在没有聚焦提示框后，提示框不消失（并没有移动它），我再研究一下。
